import org.jzy3d.colors.Color
import org.jzy3d.colors.ColorMapper
import org.jzy3d.colors.colormaps.ColorMapHotCold
import org.jzy3d.colors.colormaps.ColorMapRainbow
import org.jzy3d.colors.colormaps.ColorMapRedAndGreen
import org.jzy3d.colors.colormaps.ColorMapWhiteBlue
import org.jzy3d.colors.colormaps.ColorMapWhiteGreen
import org.jzy3d.colors.colormaps.ColorMapWhiteRed
import org.jzy3d.colors.colormaps.ColorMapWhiteYellow
import org.jzy3d.colors.colormaps.ColorMapYellowAndGreen
import org.jzy3d.colors.colormaps.ColorMapYellowAndRed
import org.jzy3d.colors.colormaps.ColorMapYellowGreen
import org.jzy3d.colors.colormaps.ColorMapYellowRed
import org.jzy3d.colors.colormaps.IColorMap
import org.jzy3d.maths.Coord3d
import org.jzy3d.plot3d.builder.Mapper
import org.jzy3d.plot3d.builder.concrete.OrthonormalGrid
import org.jzy3d.plot3d.builder.concrete.OrthonormalTessellator
import org.jzy3d.plot3d.builder.concrete.SphereTessellator
import org.jzy3d.plot3d.builder.concrete.Tessellator
import org.jzy3d.plot3d.builder.delaunay.DelaunayTessellator
import org.jzy3d.plot3d.builder.delaunay.jdt.DelaunayTessellatorJdt
import org.jzy3d.plot3d.builder.delaunay.jdt.JdtPoint
import org.jzy3d.plot3d.builder.delaunay.jdt.JdtTessellator
import org.jzy3d.plot3d.builder.delaunay.jdt.Vertex
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager2
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager3
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager4
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager5
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager6
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager7
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager8
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager9
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager10
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager11
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager12
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager13
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager14
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager15
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager16
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager17
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager18
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager19
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager20
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager21
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager22
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager23
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager24
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager25
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager26
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager27
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager28
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager29
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager30
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager31
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager32
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager33
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager34
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager35
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager36
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager37
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager38
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager39
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager40
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager41
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager42
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager43
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager44
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager45
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager46
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager47
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager48
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager49
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager50
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager51
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager52
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager53
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager54
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager55
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager56
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager57
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager58
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager59
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager60
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager61
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager62
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager63
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager64
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager65
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager66
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager67
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager68
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager69
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager70
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager71
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager72
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager73
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager74
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager75
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager76
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager77
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager78
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager79
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager80
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager81
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager82
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager83
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager84
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager85
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager86
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager87
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager88
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager89
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager90
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager91
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager92
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager93
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager94
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager95
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager96
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager97
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager98
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager99
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager100
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager101
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager102
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager103
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager104
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager105
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager106
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager107
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager108
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager109
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager110
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager111
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager112
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager113
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager114
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager115
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager116
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager117
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager118
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager119
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager120
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager121
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager122
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager123
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager124
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager125
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager126
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager127
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager128
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager129
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager130
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager131
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager132
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager133
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager134
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager135
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager136
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager137
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager138
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager139
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager140
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager141
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager142
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager143
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager144
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager145
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager146
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager147
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager148
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager149
import org.jzy3d.plot3d.builder.delaunay.jdt.VertexManager

